## addCssClass(selector = "a[data-value='landing']", class = "activeLink")
addCssClass(selector = "a[data-value='dashboard']", class = "activeLink")
addCssClass(selector = "a[data-value='reefs']", class = "activeLink")
addCssClass(selector = "a[data-value='sectors']", class = "activeLink")
addCssClass(selector = "a[data-value='nrm']", class = "activeLink")
addCssClass(selector = "a[data-value='zones']", class = "activeLink")
addCssClass(selector = "a[data-value='crontab']", class = "activeLink")
## shinyjs::disable(selector = "a[data-value='data']")
## addCssClass(selector = "a[data-value='data']", class = "inactiveLink")
## shinyjs::disable("runProcessCode")
## shinyjs::disable("runEDACode")
## shinyjs::disable(selector = "a[data-value='eda']")
## addCssClass(selector = "a[data-value='eda']", class = "inactiveLink")
## addCssClass(selector = "a[data-value='analysis']", class = "activeLink")
